### ISSUE TITLE
Slow PC: Service isn't responding

### ISSUE THREAD

**Issue by tnodir** [tnodir/fort#53]
I noticed that FF detect FortFirewallSvc when restarting service automatically and that's great 👍, BUT (Service isn't responding) message still appear from time to time 😔.
I reproduce this issues with temporary solution.
It's important to see video link please:
https://www.mediafire.com/file/5mzq6vjhwi7jmgc/Anwar-Error-video.zip/file

(Extracted from #46)

**Comment by anwar-alsilwy** [comment]
Excuse me, did you see the two videos Mr.tnodir ?
And have you any notes about them ?

**Comment by tnodir** [comment]
@anwar-alsilwy Can you please provide logs from the following folders:
- C:\Users\<NAME>\AppData\Local\Fort Firewall\logs
- C:\ProgramData\Fort Firewall\logs

**Comment by tnodir** [comment]
> What's the matter ?

I hoped that Service has some error in the logs.

Ok, I'm going to add periodical connection checking to Service...

**Comment by anwar-alsilwy** [comment]
Try to use (internet download manager) and while downloading a big file, enable group limit speed (e g 30KiB) and try to block/ allow IDM several times.
Maybe (Service isn't responding) message will appear
I hope this information will help.

**Comment by tnodir** [comment]
@anwar-alsilwy Try to test new [v3.7.3-test0](https://github.com/tnodir/fort/releases/tag/v3.7.3-test0):
- reproduce the "Service isn't responding" bug
- click on "Pause" of the FortFirewallSvc
- click on "Continue" of the FortFirewallSvc
- check the UI

**Comment by anwar-alsilwy** [comment]
> * click on "Pause" of the FortFirewallSvc
> * click on "Continue" of the FortFirewallSvc

There is no "Pause/Continue"
Did you mean "Stop/Start" ???

**Comment by tnodir** [comment]
There is "Pause/Continue" in the new v3.7.3-test0

**Comment by anwar-alsilwy** [comment]
Where ? on task manager ---> services there is only (start , stop, restart)
I did restart to my PC to see changes affect after update but still the same

![20230216_123233](https://user-images.githubusercontent.com/71539261/219326425-1794d4dd-7249-4ccd-a7b8-88cd4fa5d65b.jpg)

**Comment by tnodir** [comment]
Hm.. Try Services control panel then:
![fort](https://user-images.githubusercontent.com/303655/219327536-4bfdc620-b0be-4e72-9229-ef9405fcdbb4.jpg)

**Comment by anwar-alsilwy** [comment]
Ok here we go:
First, the new release make program UI more laggy, I hope you reverse changes to 3.7.2 because it's way better.

Second, I think "service isn't responding" issue happen directly with (Internet Download Manager) while it's downloading, ONLY WHILE IT'S DOWNLOADING!!!
When IDM stop downloading the FF working just fine,
While IDM downloading I can Allow/block other programs without issue, But when I allow/block IDM it's self, the bug will happen.
And I think it's also effect all other programs on FF program UI

It's important to see my diagnostic video please:
https://www.mediafire.com/file/l427odduhhapkxt/FortFirewall_Issue.mp4/file

Cheers 🥂

**Comment by anwar-alsilwy** [comment]
Besides: pause/resume FortFirewallSvc not resolving this issue, restarting service, is more guaranteed to resolve this issue

**Comment by anwar-alsilwy** [comment]
Briefly: this issue happen especially when I tried to block or allow IDM program WHILE IT'S DOWNLOADING ONLY.
and that's effects all other programs on FF UI.
Try to reproduce this issue with IDM, maybe you will find the solution.

Thank you so much for hard work ☺️

**Comment by tnodir** [comment]
I can't reproduce the issue with IDM.

**Comment by anwar-alsilwy** [comment]
> I can't reproduce the issue with IDM.

Ok, I will try to reproduce this issue on my friend modern PC, maybe this issue happen only on slow PCs.

**Comment by anwar-alsilwy** [comment]
Ok, after I attempted to reproduce this issue on my friend PC, Here what I found:

https://www.mediafire.com/file/krg36vw9o1bgscd/Anwar_IDM_issue.mp4/file

The message "Service isn't responding" appears on old or slow PCs, on modern PCs, the message doesn't appear but I feel a little lagging when I (allow/block) IDM.

unfortunately, you told me to disable " collect blocked connection" from the beginning.

**Comment by tnodir** [comment]
@anwar-alsilwy Thanks for checking the "Collect blocked connections" option on slow PC.
I've to optimize the blocked connections saving somehow...

**Comment by anwar-alsilwy** [comment]
Great 

> I've to optimize the blocked connections saving somehow...

Great thanks for hard work ☺️👍
But please, let the user  to choose (enable/disable) collect blocked connections, as it is now.

**Comment by tnodir** [comment]
@anwar-alsilwy Please check the [v3.7.4](https://github.com/tnodir/fort/releases/tag/v3.7.4).

**Comment by anwar-alsilwy** [comment]
Ok, thank you for your hard work 👍
I tested FF 3.7.5, I re-enable "Collect blocked connection" and test it with IDM, The message "Service isn't responding" is no longer appear anymore when I (allow/block) IDM 👍

Minor issue: in the Statics UI 'blocked connections' tab, the blocked connections is appearing as expected with a few connections, but if I block IDM, it generate hundreds of blocked connections, so Statics window stuck, I cannot clear list and auto scroll is suddenly stop, also new blocked connection not appear.

**Comment by tnodir** [comment]
> You can easily reproduce this issue by blocking IDM while downloading

Ok, let me double check it.
When I tested the IDM blocking last time, the list Clearing worked fine, but because IDM generates many blocked connections, then it looks like the list is not cleared.
But I didn't check the auto-scroll...

**Comment by anwar-alsilwy** [comment]
I completely stopped IDM, so no longer generate connections, but the list still unclear, auto scroll is stop working, and even the list no longer showing new blocked connections. Check it please 🥺

**Comment by tnodir** [comment]
> You can easily reproduce this issue by blocking IDM while downloading

Thanks, fixed in [v3.7.6](https://github.com/tnodir/fort/releases/tag/v3.7.6).

**Comment by anwar-alsilwy** [comment]
Testing...

**Comment by anwar-alsilwy** [comment]
I tried to collect blocked connections of IDM on 3.7.6
But unfortunately, bug still happen.
When IDM generate hundreds of connections, I can't clear list and also it doesn't show new blocked connections.
I thought you fixed this issue 🤔 !!

**Comment by tnodir** [comment]
> I tried to collect blocked connections of IDM on 3.7.6
> But unfortunately, bug still happen.

Yes, it was fixed in 3.7.6. I've reproduced the bug in 3.7.5.
Let me double check...

**Comment by tnodir** [comment]
- when IDM is blocked and generating tons of blocked connections, then Clearing the list seems not working: it's because list updates every 0.5 second and it fulls again after clearing
- when IDM is stopped after generating of blocked connections, then Clearing the list works as expected

**Comment by anwar-alsilwy** [comment]
> * when IDM is stopped after generating of blocked connections, then Clearing the list works as expected

Very weird !!!
I'll double check it with latest version tomorrow,
Who knows, maybe slow PC can detect this bug
Stay tuned please ...

**Comment by anwar-alsilwy** [comment]
Ok, I tested FF v3.7.8
I like the new "Disable Service controls" option, it's quite impressive. Great thanks 👍

- But unfortunately, I blocked IDM connections for a while and stop IDM completely, however clear blocked connections, stop auto scroll & cannot Collect new blocked connections issues still happen.

Maybe, I will test it on my friend modern PC.

**Comment by tnodir** [comment]
Does it work after FFw restarting?

**Comment by anwar-alsilwy** [comment]
> Does it work after FFw restarting?

No, actually it's not
It still the same.

**Comment by tnodir** [comment]
Even after both parts (service & UI) restarting?

**Comment by tnodir** [comment]
@anwar-alsilwy Please send the "FortFirewall.stat-block" file to nodir.temir@gmail.com, after reproducing the bug.

**Comment by anwar-alsilwy** [comment]
> Even after both parts (service & UI) restarting?

I reproduced issue and exit from FF UI but issue is still,
But when I exit FF UI and restart service, the blocked connections list works again as expected including collect new blocked connections/ clear list successfully/auto scroll too.
The FortFirewall.stat-block file has been sent.

**Comment by tnodir** [comment]
> The FortFirewall.stat-block file has been sent.

But that db file has no tables (file size is 4096 bytes).
Try to reproduce the bug, close FF UI and stop the Service.
Then copy the `FortFirewall.stat-block` (there should not be other `FortFirewall.stat-block-*` files).

**Comment by tnodir** [comment]
@anwar-alsilwy We can chat in telegram to troubleshoot the bug: @nodir_temir

**Comment by tnodir** [comment]
@anwar-alsilwy Please try the [v3.7.9](https://github.com/tnodir/fort/releases/tag/v3.7.9).

**Comment by anwar-alsilwy** [comment]
Testing tomorrow...

**Comment by tnodir** [comment]
@anwar-alsilwy Last sent `FortFirewall.stat-block` file is good.

Did you reproduce the bug with v3.7.9 or v3.8.0?

**Comment by anwar-alsilwy** [comment]
> Did you reproduce the bug with v3.7.9 or v3.8.0?

v3.8.0

**Comment by JadranR** [comment]
Hi, after uninstall app, all files from app folder Application data areen't
deleted?

V sre., 15. mar. 2023, 06:03 je oseba Anwar Abdulrazzaq <
***@***.***> napisala:

**Comment by anwar-alsilwy** [comment]
After uninstall, the folders of FortFirewall (under program data & user local) and all it's contents still present.

**Comment by tnodir** [comment]
> Hi, after uninstall app, all files from app folder Application data areen't deleted?

Hi. No, the data is not deleting on uninstall.

Maybe we should add option to Uninstaller to delete data in the standard path (C:\ProgramdData\Fort Firewall\)...

**Comment by tnodir** [comment]
Created #56

**Comment by tnodir** [comment]
@anwar-alsilwy Please do:
- install the [v3.8.10-test01](https://github.com/tnodir/fort/releases/tag/v3.8.10-test01)
- turn on the Options: Logs: "log debug messages" flag
- reproduce the bug
- send me all logs from Service & UI

**Comment by anwar-alsilwy** [comment]
> * reproduce the bug

You mean the issue of IDM with collect blocked connections ?

**Comment by tnodir** [comment]
> You mean the issue of IDM with collect blocked connections ?

Yes, this issue is about it.

**Comment by tnodir** [comment]
Also please use the v3.8.10-test01 (not v3.8.10), because only it contains additional debug logs.

**Comment by tnodir** [comment]
@anwar-alsilwy Please reproduce the bug with [v3.8.12-test01](https://github.com/tnodir/fort/releases/tag/v3.8.12-test01) and send me logs.

**Comment by tnodir** [comment]
Fixed in [v3.9.11](https://github.com/tnodir/fort/releases/tag/v3.9.11).

@anwar-alsilwy Please check.

I've reproduced the bug on old notebook with HDD.
